version: "3.9"

services:
    app:
        container_name: portfolio-mikel
        image: portfolio-mikel
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"